spring:
  application:
    name: xymaill-nacos-authServer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.53:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.31.53
    port: 6379
    password: xy123456
server:
  port: 20000