spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.31.25.28:3306/xymaill_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: nacos-maill-member
  cloud:
      nacos:
        discovery:
           server-addr: 172.31.25.28:8848

server-url:
  nacos-user-service: http://maill-member

server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

