spring:
  application:
    name: xymaill-nacos-elasticsearch
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.53:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 12000